on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      with:
        path: ~/.maven-
        key: ${{ runner.os }}-maven-${{ hashfiles(arg) }}
      uses: actions/cache@version


