on:
  push:
    branches:
      - develop
jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 8 for x64
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Run the Maven verify phase
        run: mvn clean package -DskipTests=true -Dcheckstyle.skip=true

      - name: Cache directory
        uses: actions/cache@v3
        with:
          path: $HOME/.m2/repository
          key: ${{ runner.os }}-cache
